---

- name: Deploy mezzanine on web
  hosts: web_servers
  vars_files:
    - secrets.yml

  pre_tasks:
    - name: Update the apt cache
      apt:
        update_cache: yes

  roles:
    - role: mezzanine
      database_host: "{{ hostvars.db.ansible_enp0s8.ipv4.address}}"
  
    - role: nginx

  post_tasks:
    - name: Notify Slack that the servers have been updated
      delegate_to: localhost
      slack:
        domain: acme.slack.com
        token: "{{ slack_token }}"
        msg: "web server {{ inventory_hostname }} configured."